#!/usr/bin/env sh

case "$1" in
off)
  sudo amixer sset 'Speaker' mute
  ;;
on)
  sudo amixer sset 'Speaker' unmute
  ;;
status)
  sudo amixer sget 'Speaker'
  ;;
*)
  cat << EOF
usage: speakers COMMAND

Commands:
  off         Mute the built-in speakers
  on          Unmute the built-in speakers
  status      Get the current status of the speakers

Examples:
  speakers off
  speakers on
  speakers status
EOF
  ;;
esac
