#!/usr/bin/env sh

print_help () {
  cat <<- "EOF"
usage: onedrive [COMMAND]

Commands:
  start       Start RClone and mount to ~/OneDrive
  stop        Kill RClone and unmount ~/OneDrive
  help        Print the help documentation

Examples
  onedrive start
  onedrive stop
  onedrive help
  onedrive
EOF
}

case "$1" in
stop)
  pkill rclone
  ;;
help)
  print_help
  ;;
start)
  if pgrep -x "rclone" > /dev/null
  then
    echo "RClone is running."
  else
    echo "Launching RClone"
    mkdir -p ~/OneDrive
    rclone --vfs-cache-mode writes mount OneDrive: ~/OneDrive --daemon
  fi
  ;;
*)
  print_help
  ;;
esac
