theme = "slick"
icons = "awesome"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
chip = "cpu_thermal-*"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
chip = "gpu_thermal-*"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {available}"

[[block]]
block = "disk_space"
path = "/mnt/NVMe"
alias = "NVMe"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {available}"

[[block]]
block = "battery"
device = "cw2015-battery"
interval = 10

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

