set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/.fzf
let g:vundle_default_git_proto = 'git'

call plug#begin()

" Theme Plugins
Plug 'crusoexia/vim-monokai'
Plug 'itchyny/lightline.vim'
Plug 'reedes/vim-colors-pencil'

" General Editing
Plug 'junegunn/goyo.vim'
Plug 'tomtom/tcomment_vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'iamcco/markdown-preview.nvim'

" Language Plugins
Plug 'fatih/vim-go'
Plug 'LnL7/vim-nix'

" Searching
Plug 'mileszs/ack.vim'
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Navigation
Plug 'scrooloose/nerdtree'

" Tool Integration
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

call plug#end()            " required
filetype plugin indent on    " required

" Change color scheme when you enter or exit goyo 
function! s:goyo_enter()
    colorscheme pencil
endfunction

function! s:goyo_leave()
    colorscheme monokai
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
" NerdTree Toggle
map <C-o> :NERDTreeToggle<CR>

" Status Bar Color Scheme
let g:lightline = {
      \ 'colorscheme': 'seoul256',
      \ }

" Other settings
colorscheme monokai
syntax on
set tabstop=2
set shiftwidth=2
set expandtab
set number
set laststatus=2
set numberwidth=4
set backspace=indent,eol,start
set nofoldenable " Disable folding in the editor, may re-enable later

" Enable spell checking by file type
autocmd BufRead,BufNewFile *.md setlocal spell spelllang=en_us

" Force proper colors (Disable Background Color Erase).
set t_ut=
